/********************************************************************
* AtlasFiles.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error AtlasFiles.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAtlasFiles();
extern void G__cpp_setup_inheritanceAtlasFiles();
extern void G__cpp_setup_typetableAtlasFiles();
extern void G__cpp_setup_memvarAtlasFiles();
extern void G__cpp_setup_globalAtlasFiles();
extern void G__cpp_setup_memfuncAtlasFiles();
extern void G__cpp_setup_funcAtlasFiles();
extern void G__set_cpp_environmentAtlasFiles();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "AtlasCanvas.h"
#include "AtlasLabels.h"
#include "AtlasStyle.h"
#include "AtlasUtils.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__AtlasFilesLN_TBuffer;
extern G__linked_taginfo G__AtlasFilesLN_TObject;
extern G__linked_taginfo G__AtlasFilesLN_TString;
extern G__linked_taginfo G__AtlasFilesLN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__AtlasFilesLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__AtlasFilesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__AtlasFilesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AtlasFilesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__AtlasFilesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AtlasFilesLN_TSubString;
extern G__linked_taginfo G__AtlasFilesLN_TPoint;
extern G__linked_taginfo G__AtlasFilesLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__AtlasFilesLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__AtlasFilesLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AtlasFilesLN_TQObject;
extern G__linked_taginfo G__AtlasFilesLN_TArray;
extern G__linked_taginfo G__AtlasFilesLN_TArrayI;
extern G__linked_taginfo G__AtlasFilesLN_TStyle;
extern G__linked_taginfo G__AtlasFilesLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__AtlasFilesLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__AtlasFilesLN_TH1;
extern G__linked_taginfo G__AtlasFilesLN_TGraphErrors;
extern G__linked_taginfo G__AtlasFilesLN_TGraphAsymmErrors;

/* STUB derived class for protected member access */
