//
// File generated by rootcint at Sun Sep  2 23:08:07 2018

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME AtlasFiles
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "AtlasFiles.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

/********************************************************
* AtlasFiles.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableAtlasFiles();

extern "C" void G__set_cpp_environmentAtlasFiles() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("AtlasCanvas.h");
  G__add_compiledheader("AtlasLabels.h");
  G__add_compiledheader("AtlasStyle.h");
  G__add_compiledheader("AtlasUtils.h");
  G__cpp_reset_tagtableAtlasFiles();
}
#include <new>
extern "C" int G__cpp_dllrevAtlasFiles() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Setting up global function */
static int G__AtlasFiles__0_127(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   const int imax = 6, dmax = 8, umax = 50;
   int objsize, type, i, icnt = 0, dcnt = 0, ucnt = 0;
   G__value *pval;
   G__int64 lval[imax] = {0};
   double dval[dmax] = {0};
   union { G__int64 lval; double dval; } u[umax] = {{0}};
   for (i = 0; i < libp->paran; i++) {
      type = G__value_get_type(&libp->para[i]);
      pval = &libp->para[i];
      if (isupper(type))
         objsize = G__LONGALLOC;
      else
         objsize = G__sizeof(pval);
      switch (type) {
         case 'c': case 'b': case 's': case 'r': objsize = sizeof(int); break;
         case 'f': objsize = sizeof(double); break;
      }
#ifdef G__VAARG_PASS_BY_REFERENCE
      if (objsize > G__VAARG_PASS_BY_REFERENCE) {
         if (pval->ref > 0x1000) {
            if (icnt < imax) {
               lval[icnt] = pval->ref; icnt++;
            } else {
               u[ucnt].lval = pval->ref; ucnt++;
            }
         } else {
            if (icnt < imax) {
               lval[icnt] = G__int(*pval); icnt++;
            } else {
               u[ucnt].lval = G__int(*pval); ucnt++;
            }
         }
         type = 'z';
      }
#endif
      switch (type) {
         case 'n': case 'm':
            if (icnt < imax) {
               lval[icnt] = (G__int64)G__Longlong(*pval); icnt++;
            } else {
               u[ucnt].lval = (G__int64)G__Longlong(*pval); ucnt++;
            } break;
         case 'f': case 'd':
            if (dcnt < dmax) {
               dval[dcnt] = G__double(*pval); dcnt++;
            } else {
               u[ucnt].dval = G__double(*pval); ucnt++;
            } break;
         case 'z': break;
         case 'u':
            if (objsize >= 16) {
               memcpy(&u[ucnt].lval, (void*)pval->obj.i, objsize);
               ucnt += objsize/8;
               break;
            }
            // objsize < 16 -> fall through
         case 'g': case 'c': case 'b': case 'r': case 's': case 'h': case 'i':
         case 'k': case 'l':
         default:
            if (icnt < imax) {
               lval[icnt] = G__int(*pval); icnt++;
            } else {
               u[ucnt].lval = G__int(*pval); ucnt++;
            } break;
      }
      if (ucnt >= 50) printf("snprintf: more than 56 var args\n");
   }
      G__letint(result7, 105, (long) snprintf((char*) G__int(libp->para[0]), (size_t) G__int(libp->para[1])
, (const char*) G__int(libp->para[2]), dval[0], dval[1], dval[2], dval[3], dval[4], dval[5], dval[6], dval[7], lval[3], lval[4], lval[5], u[0].lval, u[1].lval, u[2].lval, u[3].lval, u[4].lval, u[5].lval, u[6].lval, u[7].lval, u[8].lval, u[9].lval, u[10].lval, u[11].lval, u[12].lval, u[13].lval, u[14].lval, u[15].lval, u[16].lval, u[17].lval, u[18].lval, u[19].lval, u[20].lval, u[21].lval, u[22].lval, u[23].lval, u[24].lval, u[25].lval, u[26].lval, u[27].lval, u[28].lval, u[29].lval, u[30].lval, u[31].lval, u[32].lval, u[33].lval, u[34].lval, u[35].lval, u[36].lval, u[37].lval, u[38].lval, u[39].lval, u[40].lval, u[41].lval, u[42].lval, u[43].lval, u[44].lval, u[45].lval, u[46].lval, u[47].lval, u[48].lval, u[49].lval));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_128(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) strlcpy((char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (size_t) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_129(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) strlcat((char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (size_t) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2149(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, *(Bool_t*) G__Boolref(&libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2150(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, *(Char_t*) G__Charref(&libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2151(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, *(UChar_t*) G__UCharref(&libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2152(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, *(Short_t*) G__Shortref(&libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2153(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, *(UShort_t*) G__UShortref(&libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2154(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, *(Int_t*) G__Intref(&libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2155(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, *(UInt_t*) G__UIntref(&libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2156(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, *(Long_t*) G__Longref(&libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2157(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, *(ULong_t*) G__ULongref(&libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2158(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, *(Long64_t*) G__Longlongref(&libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2159(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, *(ULong64_t*) G__ULonglongref(&libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2160(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, *(Float_t*) G__Floatref(&libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2161(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, *(Double_t*) G__Doubleref(&libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2162(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, (Char_t*) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2163(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, *(TString*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2164(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (Bool_t) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2165(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (Char_t) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2166(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (UChar_t) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2167(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (Short_t) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2168(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (UShort_t) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2169(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (Int_t) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2170(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (UInt_t) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2171(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (Long_t) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2172(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (ULong_t) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2173(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (Long64_t) G__Longlong(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2174(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (ULong64_t) G__ULonglong(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2175(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (Float_t) G__double(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2176(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (Double_t) G__double(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2177(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (const Char_t*) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2178(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, *(TString*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2179(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (TObject*) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2229(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = operator+(*(TString*) libp->para[0].ref, *(TString*) libp->para[1].ref);
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2230(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = operator+(*(TString*) libp->para[0].ref, (const char*) G__int(libp->para[1]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2231(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = operator+((const char*) G__int(libp->para[0]), *(TString*) libp->para[1].ref);
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2232(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = operator+(*(TString*) libp->para[0].ref, (char) G__int(libp->para[1]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2233(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = operator+(*(TString*) libp->para[0].ref, (Long_t) G__int(libp->para[1]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2234(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = operator+(*(TString*) libp->para[0].ref, (ULong_t) G__int(libp->para[1]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2235(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = operator+(*(TString*) libp->para[0].ref, (Long64_t) G__Longlong(libp->para[1]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2236(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = operator+(*(TString*) libp->para[0].ref, (ULong64_t) G__ULonglong(libp->para[1]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2237(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = operator+((char) G__int(libp->para[0]), *(TString*) libp->para[1].ref);
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2238(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = operator+((Long_t) G__int(libp->para[0]), *(TString*) libp->para[1].ref);
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2239(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = operator+((ULong_t) G__int(libp->para[0]), *(TString*) libp->para[1].ref);
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2240(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = operator+((Long64_t) G__Longlong(libp->para[0]), *(TString*) libp->para[1].ref);
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2241(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = operator+((ULong64_t) G__ULonglong(libp->para[0]), *(TString*) libp->para[1].ref);
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2242(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator==(*(TString*) libp->para[0].ref, *(TString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2243(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator==(*(TString*) libp->para[0].ref, (const char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2244(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator==(*(TSubString*) libp->para[0].ref, *(TSubString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2245(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator==(*(TSubString*) libp->para[0].ref, *(TString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2246(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator==(*(TSubString*) libp->para[0].ref, (const char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2247(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (TString*) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2248(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const istream& obj = operator>>(*(istream*) libp->para[0].ref, *(TString*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2249(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const ostream& obj = operator<<(*(ostream*) libp->para[0].ref, *(TString*) libp->para[1].ref);
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2250(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, libp->para[1].ref ? *(TString**) libp->para[1].ref : *(TString**) (void*) (&G__Mlong(libp->para[1])));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2251(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ToLower(*(TString*) libp->para[0].ref);
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2252(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = ToUpper(*(TString*) libp->para[0].ref);
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2253(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) Hash(*(TString*) libp->para[0].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2254(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) Hash((TString*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2255(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) Hash((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2256(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   const int imax = 6, dmax = 8, umax = 50;
   int objsize, type, i, icnt = 0, dcnt = 0, ucnt = 0;
   G__value *pval;
   G__int64 lval[imax] = {0};
   double dval[dmax] = {0};
   union { G__int64 lval; double dval; } u[umax] = {{0}};
   for (i = 0; i < libp->paran; i++) {
      type = G__value_get_type(&libp->para[i]);
      pval = &libp->para[i];
      if (isupper(type))
         objsize = G__LONGALLOC;
      else
         objsize = G__sizeof(pval);
      switch (type) {
         case 'c': case 'b': case 's': case 'r': objsize = sizeof(int); break;
         case 'f': objsize = sizeof(double); break;
      }
#ifdef G__VAARG_PASS_BY_REFERENCE
      if (objsize > G__VAARG_PASS_BY_REFERENCE) {
         if (pval->ref > 0x1000) {
            if (icnt < imax) {
               lval[icnt] = pval->ref; icnt++;
            } else {
               u[ucnt].lval = pval->ref; ucnt++;
            }
         } else {
            if (icnt < imax) {
               lval[icnt] = G__int(*pval); icnt++;
            } else {
               u[ucnt].lval = G__int(*pval); ucnt++;
            }
         }
         type = 'z';
      }
#endif
      switch (type) {
         case 'n': case 'm':
            if (icnt < imax) {
               lval[icnt] = (G__int64)G__Longlong(*pval); icnt++;
            } else {
               u[ucnt].lval = (G__int64)G__Longlong(*pval); ucnt++;
            } break;
         case 'f': case 'd':
            if (dcnt < dmax) {
               dval[dcnt] = G__double(*pval); dcnt++;
            } else {
               u[ucnt].dval = G__double(*pval); ucnt++;
            } break;
         case 'z': break;
         case 'u':
            if (objsize >= 16) {
               memcpy(&u[ucnt].lval, (void*)pval->obj.i, objsize);
               ucnt += objsize/8;
               break;
            }
            // objsize < 16 -> fall through
         case 'g': case 'c': case 'b': case 'r': case 's': case 'h': case 'i':
         case 'k': case 'l':
         default:
            if (icnt < imax) {
               lval[icnt] = G__int(*pval); icnt++;
            } else {
               u[ucnt].lval = G__int(*pval); ucnt++;
            } break;
      }
      if (ucnt >= 50) printf("Form: more than 56 var args\n");
   }
      G__letint(result7, 67, (long) Form((const char*) G__int(libp->para[0]), dval[0], dval[1], dval[2], dval[3], dval[4], dval[5], dval[6], dval[7], lval[1], lval[2], lval[3], lval[4], lval[5], u[0].lval, u[1].lval, u[2].lval, u[3].lval, u[4].lval, u[5].lval, u[6].lval, u[7].lval, u[8].lval, u[9].lval, u[10].lval, u[11].lval, u[12].lval, u[13].lval, u[14].lval, u[15].lval, u[16].lval, u[17].lval, u[18].lval, u[19].lval, u[20].lval, u[21].lval, u[22].lval, u[23].lval, u[24].lval, u[25].lval, u[26].lval, u[27].lval, u[28].lval, u[29].lval, u[30].lval, u[31].lval, u[32].lval, u[33].lval, u[34].lval, u[35].lval, u[36].lval, u[37].lval, u[38].lval, u[39].lval, u[40].lval, u[41].lval, u[42].lval, u[43].lval, u[44].lval, u[45].lval, u[46].lval, u[47].lval, u[48].lval, u[49].lval));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2257(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   const int imax = 6, dmax = 8, umax = 50;
   int objsize, type, i, icnt = 0, dcnt = 0, ucnt = 0;
   G__value *pval;
   G__int64 lval[imax] = {0};
   double dval[dmax] = {0};
   union { G__int64 lval; double dval; } u[umax] = {{0}};
   for (i = 0; i < libp->paran; i++) {
      type = G__value_get_type(&libp->para[i]);
      pval = &libp->para[i];
      if (isupper(type))
         objsize = G__LONGALLOC;
      else
         objsize = G__sizeof(pval);
      switch (type) {
         case 'c': case 'b': case 's': case 'r': objsize = sizeof(int); break;
         case 'f': objsize = sizeof(double); break;
      }
#ifdef G__VAARG_PASS_BY_REFERENCE
      if (objsize > G__VAARG_PASS_BY_REFERENCE) {
         if (pval->ref > 0x1000) {
            if (icnt < imax) {
               lval[icnt] = pval->ref; icnt++;
            } else {
               u[ucnt].lval = pval->ref; ucnt++;
            }
         } else {
            if (icnt < imax) {
               lval[icnt] = G__int(*pval); icnt++;
            } else {
               u[ucnt].lval = G__int(*pval); ucnt++;
            }
         }
         type = 'z';
      }
#endif
      switch (type) {
         case 'n': case 'm':
            if (icnt < imax) {
               lval[icnt] = (G__int64)G__Longlong(*pval); icnt++;
            } else {
               u[ucnt].lval = (G__int64)G__Longlong(*pval); ucnt++;
            } break;
         case 'f': case 'd':
            if (dcnt < dmax) {
               dval[dcnt] = G__double(*pval); dcnt++;
            } else {
               u[ucnt].dval = G__double(*pval); ucnt++;
            } break;
         case 'z': break;
         case 'u':
            if (objsize >= 16) {
               memcpy(&u[ucnt].lval, (void*)pval->obj.i, objsize);
               ucnt += objsize/8;
               break;
            }
            // objsize < 16 -> fall through
         case 'g': case 'c': case 'b': case 'r': case 's': case 'h': case 'i':
         case 'k': case 'l':
         default:
            if (icnt < imax) {
               lval[icnt] = G__int(*pval); icnt++;
            } else {
               u[ucnt].lval = G__int(*pval); ucnt++;
            } break;
      }
      if (ucnt >= 50) printf("Printf: more than 56 var args\n");
   }
      Printf((const char*) G__int(libp->para[0]), dval[0], dval[1], dval[2], dval[3], dval[4], dval[5], dval[6], dval[7], lval[1], lval[2], lval[3], lval[4], lval[5], u[0].lval, u[1].lval, u[2].lval, u[3].lval, u[4].lval, u[5].lval, u[6].lval, u[7].lval, u[8].lval, u[9].lval, u[10].lval, u[11].lval, u[12].lval, u[13].lval, u[14].lval, u[15].lval, u[16].lval, u[17].lval, u[18].lval, u[19].lval, u[20].lval, u[21].lval, u[22].lval, u[23].lval, u[24].lval, u[25].lval, u[26].lval, u[27].lval, u[28].lval, u[29].lval, u[30].lval, u[31].lval, u[32].lval, u[33].lval, u[34].lval, u[35].lval, u[36].lval, u[37].lval, u[38].lval, u[39].lval, u[40].lval, u[41].lval, u[42].lval, u[43].lval, u[44].lval, u[45].lval, u[46].lval, u[47].lval, u[48].lval, u[49].lval);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2258(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 67, (long) Strip((const char*) G__int(libp->para[0]), (char) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 67, (long) Strip((const char*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2259(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) StrDup((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2260(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Compress((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2261(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) EscChar((const char*) G__int(libp->para[0]), (char*) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (char*) G__int(libp->para[3])
, (char) G__int(libp->para[4])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2262(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) UnEscChar((const char*) G__int(libp->para[0]), (char*) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (char*) G__int(libp->para[3])
, (char) G__int(libp->para[4])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2263(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator!=(*(TString*) libp->para[0].ref, *(TString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2264(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator<(*(TString*) libp->para[0].ref, *(TString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2265(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator>(*(TString*) libp->para[0].ref, *(TString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2266(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator<=(*(TString*) libp->para[0].ref, *(TString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2267(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator>=(*(TString*) libp->para[0].ref, *(TString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2268(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator!=(*(TString*) libp->para[0].ref, (const char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2269(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator<(*(TString*) libp->para[0].ref, (const char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2270(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator>(*(TString*) libp->para[0].ref, (const char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2271(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator<=(*(TString*) libp->para[0].ref, (const char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2272(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator>=(*(TString*) libp->para[0].ref, (const char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2273(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator==((const char*) G__int(libp->para[0]), *(TString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2274(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator!=((const char*) G__int(libp->para[0]), *(TString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2275(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator<((const char*) G__int(libp->para[0]), *(TString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2276(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator>((const char*) G__int(libp->para[0]), *(TString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2277(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator<=((const char*) G__int(libp->para[0]), *(TString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2278(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator>=((const char*) G__int(libp->para[0]), *(TString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2279(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator==(*(TString*) libp->para[0].ref, *(TSubString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2280(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator==((const char*) G__int(libp->para[0]), *(TSubString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2281(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator!=(*(TSubString*) libp->para[0].ref, (const char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2282(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator!=(*(TSubString*) libp->para[0].ref, *(TString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2283(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator!=(*(TSubString*) libp->para[0].ref, *(TSubString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2284(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator!=(*(TString*) libp->para[0].ref, *(TSubString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2285(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator!=((const char*) G__int(libp->para[0]), *(TSubString*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2354(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ConnectCINT((TQObject*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2355(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator==(*(TPoint*) libp->para[0].ref, *(TPoint*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2356(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) operator!=(*(TPoint*) libp->para[0].ref, *(TPoint*) libp->para[1].ref));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2357(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      ATLASLabel((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (const char*) G__int(libp->para[2]), (Color_t) G__int(libp->para[3])
, (const char*) G__int(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      ATLASLabel((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (const char*) G__int(libp->para[2]), (Color_t) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ATLASLabel((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (const char*) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ATLASLabel((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2358(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      ATLASLabelOld((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (bool) G__int(libp->para[2]), (Color_t) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ATLASLabelOld((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (bool) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ATLASLabelOld((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2359(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 5:
      ATLASLabelNew((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (const char*) G__int(libp->para[2]), (Color_t) G__int(libp->para[3])
, (float) G__double(libp->para[4]));
      G__setnull(result7);
      break;
   case 4:
      ATLASLabelNew((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (const char*) G__int(libp->para[2]), (Color_t) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ATLASLabelNew((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (const char*) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ATLASLabelNew((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2360(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      ATLASVersion((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Color_t) G__int(libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ATLASVersion((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ATLASVersion((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ATLASVersion((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ATLASVersion();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2361(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (TArray*) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2362(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, libp->para[1].ref ? *(TArray**) libp->para[1].ref : *(TArray**) (void*) (&G__Mlong(libp->para[1])));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2363(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator>>(*(TBuffer*) libp->para[0].ref, libp->para[1].ref ? *(TArrayI**) libp->para[1].ref : *(TArrayI**) (void*) (&G__Mlong(libp->para[1])));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2364(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const TBuffer& obj = operator<<(*(TBuffer*) libp->para[0].ref, (TArrayI*) G__int(libp->para[1]));
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2365(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      SetAtlasStyle();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2366(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) AtlasStyle());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2367(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      ATLAS_LABEL((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Color_t) G__int(libp->para[2]));
      G__setnull(result7);
      break;
   case 2:
      ATLAS_LABEL((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2368(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) myTGraphErrorsDivide((TGraphErrors*) G__int(libp->para[0]), (TGraphErrors*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2369(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) myTGraphErrorsDivide((TGraphAsymmErrors*) G__int(libp->para[0]), (TGraphAsymmErrors*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2370(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) myMakeBand((TGraphErrors*) G__int(libp->para[0]), (TGraphErrors*) G__int(libp->para[1])
, (TGraphErrors*) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2371(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      myAddtoBand((TGraphErrors*) G__int(libp->para[0]), (TGraphAsymmErrors*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2372(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TH1TOTGraph((TH1*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2373(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      myText((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Color_t) G__int(libp->para[2]), (const char*) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2374(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      myBoxText((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Int_t) G__int(libp->para[3])
, (const char*) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__AtlasFiles__0_2375(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 6:
      myMarkerText((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Int_t) G__int(libp->para[3])
, (const char*) G__int(libp->para[4]), (Float_t) G__double(libp->para[5]));
      G__setnull(result7);
      break;
   case 5:
      myMarkerText((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Int_t) G__int(libp->para[2]), (Int_t) G__int(libp->para[3])
, (const char*) G__int(libp->para[4]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncAtlasFiles {
 public:
  G__Sizep2memfuncAtlasFiles(): p(&G__Sizep2memfuncAtlasFiles::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncAtlasFiles::*p)();
};

size_t G__get_sizep2memfuncAtlasFiles()
{
  G__Sizep2memfuncAtlasFiles a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceAtlasFiles() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableAtlasFiles() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 8 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 8 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("Color_t",115,-1,0,-1);
   G__setnewtype(-1,"Color number (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__AtlasFilesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AtlasFilesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AtlasFilesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AtlasFilesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AtlasFilesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__AtlasFilesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AtlasFilesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AtlasFilesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AtlasFilesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AtlasFilesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__AtlasFilesLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__AtlasFilesLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__AtlasFilesLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__AtlasFilesLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AtlasFilesLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__AtlasFilesLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__AtlasFilesLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__AtlasFilesLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__AtlasFilesLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__AtlasFilesLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvarAtlasFiles() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/

/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncAtlasFiles() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalAtlasFiles() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
   G__memfunc_setup("snprintf", 884, G__AtlasFiles__0_127, 105, -1, -1, 0, 3, 8, 1, 0, 
"C - - 0 - string k - 'size_t' 0 - length "
"C - - 10 - format", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("strlcpy", 785, G__AtlasFiles__0_128, 107, -1, G__defined_typename("size_t"), 0, 3, 1, 1, 0, 
"C - - 0 - dst C - - 10 - src "
"k - 'size_t' 0 - siz", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("strlcat", 765, G__AtlasFiles__0_129, 107, -1, G__defined_typename("size_t"), 0, 3, 1, 1, 0, 
"C - - 0 - dst C - - 10 - src "
"k - 'size_t' 0 - siz", (char*) NULL
, (void*) NULL, 0);
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2149, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf g - 'Bool_t' 1 - b", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2150, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf c - 'Char_t' 1 - c", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2151, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf b - 'UChar_t' 1 - c", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2152, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf s - 'Short_t' 1 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2153, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf r - 'UShort_t' 1 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2154, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf i - 'Int_t' 1 - i", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2155, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf h - 'UInt_t' 1 - i", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2156, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf l - 'Long_t' 1 - l", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2157, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf k - 'ULong_t' 1 - l", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2158, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf n - 'Long64_t' 1 - l", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2159, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf m - 'ULong64_t' 1 - l", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2160, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf f - 'Float_t' 1 - f", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2161, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf d - 'Double_t' 1 - d", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2162, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf C - 'Char_t' 0 - c", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2163, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf u 'TString' - 1 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2164, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf g - 'Bool_t' 0 - b", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2165, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf c - 'Char_t' 0 - c", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2166, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf b - 'UChar_t' 0 - c", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2167, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf s - 'Short_t' 0 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2168, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf r - 'UShort_t' 0 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2169, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf i - 'Int_t' 0 - i", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2170, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf h - 'UInt_t' 0 - i", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2171, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf l - 'Long_t' 0 - l", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2172, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf k - 'ULong_t' 0 - l", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2173, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf n - 'Long64_t' 0 - l", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2174, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf m - 'ULong64_t' 0 - l", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2175, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf f - 'Float_t' 0 - f", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2176, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf d - 'Double_t' 0 - d", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2177, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf C - 'Char_t' 10 - c", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2178, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf u 'TString' - 11 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2179, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf U 'TObject' - 10 - obj", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator+", 919, G__AtlasFiles__0_2229, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator+", 919, G__AtlasFiles__0_2230, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s C - - 10 - cs", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator+", 919, G__AtlasFiles__0_2231, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 2, 1, 1, 0, 
"C - - 10 - cs u 'TString' - 11 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator+", 919, G__AtlasFiles__0_2232, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s c - - 0 - c", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator+", 919, G__AtlasFiles__0_2233, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s l - 'Long_t' 0 - i", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator+", 919, G__AtlasFiles__0_2234, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s k - 'ULong_t' 0 - i", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator+", 919, G__AtlasFiles__0_2235, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s n - 'Long64_t' 0 - i", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator+", 919, G__AtlasFiles__0_2236, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s m - 'ULong64_t' 0 - i", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator+", 919, G__AtlasFiles__0_2237, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 2, 1, 1, 0, 
"c - - 0 - c u 'TString' - 11 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator+", 919, G__AtlasFiles__0_2238, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 2, 1, 1, 0, 
"l - 'Long_t' 0 - i u 'TString' - 11 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator+", 919, G__AtlasFiles__0_2239, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 2, 1, 1, 0, 
"k - 'ULong_t' 0 - i u 'TString' - 11 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator+", 919, G__AtlasFiles__0_2240, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 2, 1, 1, 0, 
"n - 'Long64_t' 0 - i u 'TString' - 11 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator+", 919, G__AtlasFiles__0_2241, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 2, 1, 1, 0, 
"m - 'ULong64_t' 0 - i u 'TString' - 11 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator==", 998, G__AtlasFiles__0_2242, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
}

static void G__cpp_setup_func22() {
   G__memfunc_setup("operator==", 998, G__AtlasFiles__0_2243, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 C - - 10 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator==", 998, G__AtlasFiles__0_2244, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TSubString' - 11 - s1 u 'TSubString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator==", 998, G__AtlasFiles__0_2245, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TSubString' - 11 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator==", 998, G__AtlasFiles__0_2246, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TSubString' - 11 - s1 C - - 10 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2247, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - b U 'TString' - 10 - obj", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2248, 117, G__get_linked_tagnum(&G__AtlasFilesLN_basic_istreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("istream"), 1, 2, 1, 1, 0, 
"u 'basic_istream<char,char_traits<char> >' 'istream' 1 - str u 'TString' - 1 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2249, 117, G__get_linked_tagnum(&G__AtlasFilesLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR), G__defined_typename("ostream"), 1, 2, 1, 1, 0, 
"u 'basic_ostream<char,char_traits<char> >' 'ostream' 1 - str u 'TString' - 11 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2250, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf U 'TString' - 1 - sp", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("ToLower", 716, G__AtlasFiles__0_2251, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 1, 1, 1, 0, "u 'TString' - 11 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("ToUpper", 719, G__AtlasFiles__0_2252, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TString), -1, 0, 1, 1, 1, 0, "u 'TString' - 11 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("Hash", 388, G__AtlasFiles__0_2253, 104, -1, G__defined_typename("UInt_t"), 0, 1, 1, 1, 0, "u 'TString' - 11 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("Hash", 388, G__AtlasFiles__0_2254, 104, -1, G__defined_typename("UInt_t"), 0, 1, 1, 1, 0, "U 'TString' - 10 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("Hash", 388, G__AtlasFiles__0_2255, 104, -1, G__defined_typename("UInt_t"), 0, 1, 1, 1, 0, "C - - 10 - s", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("Form", 404, G__AtlasFiles__0_2256, 67, -1, -1, 0, 1, 8, 1, 0, "C - - 10 - fmt", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("Printf", 627, G__AtlasFiles__0_2257, 121, -1, -1, 0, 1, 8, 1, 0, "C - - 10 - fmt", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("Strip", 530, G__AtlasFiles__0_2258, 67, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - str c - - 0 '' '' c", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("StrDup", 610, G__AtlasFiles__0_2259, 67, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - str", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("Compress", 844, G__AtlasFiles__0_2260, 67, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - str", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("EscChar", 665, G__AtlasFiles__0_2261, 105, -1, -1, 0, 5, 1, 1, 0, 
"C - - 10 - src C - - 0 - dst "
"i - - 0 - dstlen C - - 0 - specchars "
"c - - 0 - escchar", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("UnEscChar", 860, G__AtlasFiles__0_2262, 105, -1, -1, 0, 5, 1, 1, 0, 
"C - - 10 - src C - - 0 - dst "
"i - - 0 - dstlen C - - 0 - specchars "
"c - - 0 - escchar", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator!=", 970, G__AtlasFiles__0_2263, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<", 936, G__AtlasFiles__0_2264, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>", 938, G__AtlasFiles__0_2265, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<=", 997, G__AtlasFiles__0_2266, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>=", 999, G__AtlasFiles__0_2267, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator!=", 970, G__AtlasFiles__0_2268, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 C - - 10 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<", 936, G__AtlasFiles__0_2269, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 C - - 10 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>", 938, G__AtlasFiles__0_2270, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 C - - 10 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<=", 997, G__AtlasFiles__0_2271, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 C - - 10 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>=", 999, G__AtlasFiles__0_2272, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 C - - 10 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator==", 998, G__AtlasFiles__0_2273, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"C - - 10 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator!=", 970, G__AtlasFiles__0_2274, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"C - - 10 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<", 936, G__AtlasFiles__0_2275, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"C - - 10 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>", 938, G__AtlasFiles__0_2276, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"C - - 10 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<=", 997, G__AtlasFiles__0_2277, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"C - - 10 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>=", 999, G__AtlasFiles__0_2278, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"C - - 10 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator==", 998, G__AtlasFiles__0_2279, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 u 'TSubString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator==", 998, G__AtlasFiles__0_2280, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"C - - 10 - s1 u 'TSubString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator!=", 970, G__AtlasFiles__0_2281, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TSubString' - 11 - s1 C - - 10 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator!=", 970, G__AtlasFiles__0_2282, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TSubString' - 11 - s1 u 'TString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator!=", 970, G__AtlasFiles__0_2283, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TSubString' - 11 - s1 u 'TSubString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator!=", 970, G__AtlasFiles__0_2284, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"u 'TString' - 11 - s1 u 'TSubString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator!=", 970, G__AtlasFiles__0_2285, 103, -1, G__defined_typename("Bool_t"), 0, 2, 1, 1, 0, 
"C - - 10 - s1 u 'TSubString' - 11 - s2", (char*) NULL
, (void*) NULL, 0);
}

static void G__cpp_setup_func23() {
   G__memfunc_setup("ConnectCINT", 1016, G__AtlasFiles__0_2354, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"U 'TQObject' - 0 - sender C - - 10 - signal "
"C - - 10 - slot", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator==", 998, G__AtlasFiles__0_2355, 103, -1, -1, 0, 2, 1, 1, 0, 
"u 'TPoint' - 11 - p1 u 'TPoint' - 11 - p2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator!=", 970, G__AtlasFiles__0_2356, 103, -1, -1, 0, 2, 1, 1, 0, 
"u 'TPoint' - 11 - p1 u 'TPoint' - 11 - p2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("ATLASLabel", 853, G__AtlasFiles__0_2357, 121, -1, -1, 0, 5, 1, 1, 0, 
"d - 'Double_t' 0 - x d - 'Double_t' 0 - y "
"C - - 10 'NULL' text s - 'Color_t' 0 '1' color "
"C - - 10 'NULL' channelname", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("ATLASLabelOld", 1140, G__AtlasFiles__0_2358, 121, -1, -1, 0, 4, 1, 1, 0, 
"d - 'Double_t' 0 - x d - 'Double_t' 0 - y "
"g - - 0 'false' Preliminary s - 'Color_t' 0 '1' color", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("ATLASLabelNew", 1151, G__AtlasFiles__0_2359, 121, -1, -1, 0, 5, 1, 1, 0, 
"d - 'Double_t' 0 - x d - 'Double_t' 0 - y "
"C - - 10 'NULL' text s - 'Color_t' 0 '1' color "
"f - - 0 '0' text_size", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("ATLASVersion", 1115, G__AtlasFiles__0_2360, 121, -1, -1, 0, 4, 1, 1, 0, 
"C - - 10 'NULL' version d - 'Double_t' 0 '0.88' x "
"d - 'Double_t' 0 '0.975' y s - 'Color_t' 0 '1' color", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2361, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - b U 'TArray' - 10 - obj", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2362, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf U 'TArray' - 1 - obj", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator>>", 1000, G__AtlasFiles__0_2363, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf U 'TArrayI' - 1 - obj", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("operator<<", 996, G__AtlasFiles__0_2364, 117, G__get_linked_tagnum(&G__AtlasFilesLN_TBuffer), -1, 1, 2, 1, 1, 0, 
"u 'TBuffer' - 1 - buf U 'TArrayI' - 10 - obj", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("SetAtlasStyle", 1330, G__AtlasFiles__0_2365, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("AtlasStyle", 1030, G__AtlasFiles__0_2366, 85, G__get_linked_tagnum(&G__AtlasFilesLN_TStyle), -1, 0, 0, 1, 1, 0, "", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("ATLAS_LABEL", 820, G__AtlasFiles__0_2367, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - 'Double_t' 0 - x d - 'Double_t' 0 - y "
"s - 'Color_t' 0 '1' color", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("myTGraphErrorsDivide", 2046, G__AtlasFiles__0_2368, 85, G__get_linked_tagnum(&G__AtlasFilesLN_TGraphErrors), -1, 0, 2, 1, 1, 0, 
"U 'TGraphErrors' - 0 - g1 U 'TGraphErrors' - 0 - g2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("myTGraphErrorsDivide", 2046, G__AtlasFiles__0_2369, 85, G__get_linked_tagnum(&G__AtlasFilesLN_TGraphAsymmErrors), -1, 0, 2, 1, 1, 0, 
"U 'TGraphAsymmErrors' - 0 - g1 U 'TGraphAsymmErrors' - 0 - g2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("myMakeBand", 985, G__AtlasFiles__0_2370, 85, G__get_linked_tagnum(&G__AtlasFilesLN_TGraphAsymmErrors), -1, 0, 3, 1, 1, 0, 
"U 'TGraphErrors' - 0 - g0 U 'TGraphErrors' - 0 - g1 "
"U 'TGraphErrors' - 0 - g2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("myAddtoBand", 1095, G__AtlasFiles__0_2371, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TGraphErrors' - 0 - g1 U 'TGraphAsymmErrors' - 0 - g2", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("TH1TOTGraph", 950, G__AtlasFiles__0_2372, 85, G__get_linked_tagnum(&G__AtlasFilesLN_TGraphErrors), -1, 0, 1, 1, 1, 0, "U 'TH1' - 0 - h1", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("myText", 651, G__AtlasFiles__0_2373, 121, -1, -1, 0, 4, 1, 1, 0, 
"d - 'Double_t' 0 - x d - 'Double_t' 0 - y "
"s - 'Color_t' 0 - color C - - 10 - text", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("myBoxText", 948, G__AtlasFiles__0_2374, 121, -1, -1, 0, 5, 1, 1, 0, 
"d - 'Double_t' 0 - x d - 'Double_t' 0 - y "
"d - 'Double_t' 0 - boxsize i - 'Int_t' 0 - mcolor "
"C - - 10 - text", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("myMarkerText", 1261, G__AtlasFiles__0_2375, 121, -1, -1, 0, 6, 1, 1, 0, 
"d - 'Double_t' 0 - x d - 'Double_t' 0 - y "
"i - 'Int_t' 0 - color i - 'Int_t' 0 - mstyle "
"C - - 10 - text f - 'Float_t' 0 '2.' msize", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcAtlasFiles() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__AtlasFilesLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_basic_istreamlEcharcOchar_traitslEchargRsPgR = { "basic_istream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR = { "basic_ostream<char,char_traits<char> >" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_TSubString = { "TSubString" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_TPoint = { "TPoint" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__AtlasFilesLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_TArray = { "TArray" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_TArrayI = { "TArrayI" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_TStyle = { "TStyle" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_TGraphErrors = { "TGraphErrors" , 99 , -1 };
G__linked_taginfo G__AtlasFilesLN_TGraphAsymmErrors = { "TGraphAsymmErrors" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableAtlasFiles() {
  G__AtlasFilesLN_TBuffer.tagnum = -1 ;
  G__AtlasFilesLN_TObject.tagnum = -1 ;
  G__AtlasFilesLN_TString.tagnum = -1 ;
  G__AtlasFilesLN_basic_istreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__AtlasFilesLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR.tagnum = -1 ;
  G__AtlasFilesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__AtlasFilesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AtlasFilesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__AtlasFilesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AtlasFilesLN_TSubString.tagnum = -1 ;
  G__AtlasFilesLN_TPoint.tagnum = -1 ;
  G__AtlasFilesLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__AtlasFilesLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__AtlasFilesLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__AtlasFilesLN_TQObject.tagnum = -1 ;
  G__AtlasFilesLN_TArray.tagnum = -1 ;
  G__AtlasFilesLN_TArrayI.tagnum = -1 ;
  G__AtlasFilesLN_TStyle.tagnum = -1 ;
  G__AtlasFilesLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__AtlasFilesLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__AtlasFilesLN_TH1.tagnum = -1 ;
  G__AtlasFilesLN_TGraphErrors.tagnum = -1 ;
  G__AtlasFilesLN_TGraphAsymmErrors.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableAtlasFiles() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_TObject);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_TString);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_basic_istreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_TSubString);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_TPoint);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_TQObject);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_TArray);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_TArrayI);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_TStyle);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_TH1);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_TGraphErrors);
   G__get_linked_tagnum_fwd(&G__AtlasFilesLN_TGraphAsymmErrors);
}
extern "C" void G__cpp_setupAtlasFiles(void) {
  G__check_setup_version(30051515,"G__cpp_setupAtlasFiles()");
  G__set_cpp_environmentAtlasFiles();
  G__cpp_setup_tagtableAtlasFiles();

  G__cpp_setup_inheritanceAtlasFiles();

  G__cpp_setup_typetableAtlasFiles();

  G__cpp_setup_memvarAtlasFiles();

  G__cpp_setup_memfuncAtlasFiles();
  G__cpp_setup_globalAtlasFiles();
  G__cpp_setup_funcAtlasFiles();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncAtlasFiles();
  return;
}
class G__cpp_setup_initAtlasFiles {
  public:
    G__cpp_setup_initAtlasFiles() { G__add_setup_func("AtlasFiles",(G__incsetup)(&G__cpp_setupAtlasFiles)); G__call_setup_funcs(); }
   ~G__cpp_setup_initAtlasFiles() { G__remove_setup_func("AtlasFiles"); }
};
G__cpp_setup_initAtlasFiles G__cpp_setup_initializerAtlasFiles;

